// src/marqy.tsx
import * as React from 'react'

export interface MarqyProps extends React.ComponentPropsWithoutRef<'div'> {
  speed?: number
  direction?: 'left' | 'right' | 'up' | 'down'
  pauseOnHover?: boolean
  manual?: boolean
  children: React.ReactNode
}

export function Marqy({
  speed = 0.5,
  direction = 'left',
  pauseOnHover,
  manual = false,
  children,
  ...rest
}: MarqyProps): React.ReactElement {
  const [reps, setReps] = React.useState(1)

  const [container, containerDimensions] = useDimensions()
  const [item, itemDimensions] = useDimensions()

  const isVertical = direction === 'up' || direction === 'down'

  const getAnimationDuration = React.useCallback(
    (itemDimension: number) => {
      return `${((itemDimension ?? 0) * reps) / (100 * speed)}s`
    },
    [reps, speed]
  )

  React.useEffect(() => {
    if (!isVertical && containerDimensions.width && itemDimensions.width) {
      setReps(Math.ceil(containerDimensions.width / itemDimensions.width))
    }
    if (isVertical && containerDimensions.height && itemDimensions.height) {
      setReps(Math.ceil(containerDimensions.height / itemDimensions.height))
    }
  }, [isVertical, containerDimensions, itemDimensions])

  return (
    <div
      ref={container}
      data-marqy=""
      data-direction={direction}
      data-pause-on-hover={pauseOnHover ? '' : null}
      {...rest}
    >
      <div data-marqy-inner="">
        {new Array(2).fill(0).map((_, clone) => (
          <div
            key={clone}
            data-marqy-content=""
            {...(manual
              ? { 'data-marqy-static': getAnimationDuration(isVertical ? itemDimensions.height : itemDimensions.width) }
              : { style: { animationDuration: getAnimationDuration(isVertical ? itemDimensions.height : itemDimensions.width) } }
            )}
          >
            {new Array(reps).fill(0).map((_, rep) => {
              const isFirstItem = clone === 0 && rep === 0
              return (
                <div
                  key={rep}
                  ref={isFirstItem ? item : null}
                  aria-hidden={!isFirstItem || null}
                  data-marqy-item=""
                >
                  {children}
                </div>
              )
            })}
          </div>
        ))}
      </div>
    </div>
  )
}

function useDimensions() {
  const [dimensions, setDimensions] = React.useState({ width: 0, height: 0 })
  const observer = React.useRef<ResizeObserver | null>(null)

  const ref = React.useCallback((node: HTMLElement | null) => {
    observer.current?.disconnect()
    if (!node) return
    observer.current = new ResizeObserver(([entry]) =>
      setDimensions({
        width: entry.contentRect.width,
        height: entry.contentRect.height,
      })
    )
    observer.current.observe(node)
  }, [])

  return [ref, dimensions] as const
}

// src/svelte/Marqy.svelte
<script lang="ts">
  import {
    type MarqyDirection,
    calcReps,
    calcAnimationDuration,
    createResizeObserver,
  } from '../core'
  import type { Snippet } from 'svelte'

  interface Props {
    speed?: number
    direction?: MarqyDirection
    pauseOnHover?: boolean
    manual?: boolean
    children: Snippet
    [key: string]: unknown
  }

  let {
    speed = 0.5,
    direction = 'left' as MarqyDirection,
    pauseOnHover = false,
    manual = false,
    children,
    ...rest
  }: Props = $props()

  let containerEl = $state<HTMLElement | null>(null)
  let containerDims = $state({ width: 0, height: 0 })
  let itemDims = $state({ width: 0, height: 0 })
  let reps = $state(1)

  const isVertical = $derived(direction === 'up' || direction === 'down')

  const animationDuration = $derived(
    calcAnimationDuration(
      isVertical ? itemDims.height : itemDims.width,
      reps,
      speed
    )
  )

  $effect(() => {
    if (!containerEl) return
    return createResizeObserver(containerEl, (d) => {
      containerDims = d
    })
  })

  $effect(() => {
    const cSize = isVertical ? containerDims.height : containerDims.width
    const iSize = isVertical ? itemDims.height : itemDims.width
    reps = calcReps(cSize, iSize)
  })

  function observeFirstItem(node: HTMLElement, isFirst: boolean) {
    if (!isFirst) return {}
    const cleanup = createResizeObserver(node, (d) => {
      itemDims = d
    })
    return { destroy: cleanup }
  }
</script>

<div
  bind:this={containerEl}
  data-marqy=""
  data-direction={direction}
  data-pause-on-hover={pauseOnHover ? '' : undefined}
  {...rest}
>
  <div data-marqy-inner="">
    {#each [0, 1] as clone}
      <div
        data-marqy-content=""
        {...manual
          ? { 'data-marqy-static': animationDuration }
          : { style: `animation-duration: ${animationDuration}` }}
      >
        {#each Array.from({ length: reps }, (_, i) => i) as rep}
          <div
            use:observeFirstItem={clone === 0 && rep === 0}
            aria-hidden={!(clone === 0 && rep === 0) || undefined}
            data-marqy-item=""
          >
            {@render children()}
          </div>
        {/each}
      </div>
    {/each}
  </div>
</div>
