// src/svelte/Marqy.svelte
<script lang="ts">
  import {
    type MarqyDirection,
    calcReps,
    calcAnimationDuration,
    createResizeObserver,
  } from '../core'
  import type { Snippet } from 'svelte'

  interface Props {
    speed?: number
    direction?: MarqyDirection
    pauseOnHover?: boolean
    manual?: boolean
    children: Snippet
    [key: string]: unknown
  }

  let {
    speed = 0.5,
    direction = 'left' as MarqyDirection,
    pauseOnHover = false,
    manual = false,
    children,
    ...rest
  }: Props = $props()

  let containerEl = $state<HTMLElement | null>(null)
  let containerDims = $state({ width: 0, height: 0 })
  let itemDims = $state({ width: 0, height: 0 })
  let reps = $state(1)

  const isVertical = $derived(direction === 'up' || direction === 'down')

  const animationDuration = $derived(
    calcAnimationDuration(
      isVertical ? itemDims.height : itemDims.width,
      reps,
      speed
    )
  )

  $effect(() => {
    if (!containerEl) return
    return createResizeObserver(containerEl, (d) => {
      containerDims = d
    })
  })

  $effect(() => {
    const cSize = isVertical ? containerDims.height : containerDims.width
    const iSize = isVertical ? itemDims.height : itemDims.width
    reps = calcReps(cSize, iSize)
  })

  function observeFirstItem(node: HTMLElement, isFirst: boolean) {
    if (!isFirst) return {}
    const cleanup = createResizeObserver(node, (d) => {
      itemDims = d
    })
    return { destroy: cleanup }
  }
</script>

<div
  bind:this={containerEl}
  data-marqy=""
  data-direction={direction}
  data-pause-on-hover={pauseOnHover ? '' : undefined}
  {...rest}
>
  <div data-marqy-inner="">
    {#each [0, 1] as clone}
      <div
        data-marqy-content=""
        {...manual
          ? { 'data-marqy-static': animationDuration }
          : { style: `animation-duration: ${animationDuration}` }}
      >
        {#each Array.from({ length: reps }, (_, i) => i) as rep}
          <div
            use:observeFirstItem={clone === 0 && rep === 0}
            aria-hidden={!(clone === 0 && rep === 0) || undefined}
            data-marqy-item=""
          >
            {@render children()}
          </div>
        {/each}
      </div>
    {/each}
  </div>
</div>

// src/vue/Marqy.vue
<script setup lang="ts">
import { ref, computed, watch, onUnmounted } from 'vue'
import {
  type MarqyDirection,
  calcReps,
  calcAnimationDuration,
  createResizeObserver,
} from '../core'

interface Props {
  speed?: number
  direction?: MarqyDirection
  pauseOnHover?: boolean
  manual?: boolean
}

const props = withDefaults(defineProps<Props>(), {
  speed: 0.5,
  direction: 'left',
  pauseOnHover: false,
  manual: false,
})

const containerRef = ref<HTMLElement | null>(null)
const itemRef = ref<HTMLElement | null>(null)
const containerDims = ref({ width: 0, height: 0 })
const itemDims = ref({ width: 0, height: 0 })
const reps = ref(1)

const isVertical = computed(
  () => props.direction === 'up' || props.direction === 'down'
)

const animationDuration = computed(() =>
  calcAnimationDuration(
    isVertical.value ? itemDims.value.height : itemDims.value.width,
    reps.value,
    props.speed
  )
)

let cleanupContainer: (() => void) | null = null
let cleanupItem: (() => void) | null = null

watch(containerRef, (el) => {
  cleanupContainer?.()
  cleanupContainer = null
  if (el) cleanupContainer = createResizeObserver(el, (d) => { containerDims.value = d })
})

watch(itemRef, (el) => {
  cleanupItem?.()
  cleanupItem = null
  if (el) cleanupItem = createResizeObserver(el, (d) => { itemDims.value = d })
})

watch([containerDims, itemDims, isVertical], () => {
  const cSize = isVertical.value ? containerDims.value.height : containerDims.value.width
  const iSize = isVertical.value ? itemDims.value.height : itemDims.value.width
  reps.value = calcReps(cSize, iSize)
})

onUnmounted(() => {
  cleanupContainer?.()
  cleanupItem?.()
})
</script>

<template>
  <div
    ref="containerRef"
    data-marqy=""
    :data-direction="direction"
    :data-pause-on-hover="pauseOnHover ? '' : undefined"
    v-bind="$attrs"
  >
    <div data-marqy-inner="">
      <div
        v-for="clone in [0, 1]"
        :key="clone"
        data-marqy-content=""
        v-bind="
          manual
            ? { 'data-marqy-static': animationDuration }
            : { style: `animation-duration: ${animationDuration}` }
        "
      >
        <div
          v-for="rep in Array.from({ length: reps }, (_, i) => i)"
          :key="rep"
          :ref="(el) => { if (clone === 0 && rep === 0) itemRef = el as HTMLElement | null }"
          :aria-hidden="!(clone === 0 && rep === 0) || undefined"
          data-marqy-item=""
        >
          <slot />
        </div>
      </div>
    </div>
  </div>
</template>
